const getColumnTemplates = () => ({
  todo: {
    ColumnId: Date.now().toString(),
    Type: 'todo',
    Name: 'Todo List',
    Description: 'Todo list created on backend',
    EmojiIcon: 'ListTodo',
    NameVisible: true,
    Chosen: {
      global: [],
    },
    Options: ['Option 1', 'Option 2'],
    TagColors: {
      'Option 1': 'blue',
      'Option 2': 'green',
    },
    Width: 150,
  },
  checkbox: {
    ColumnId: Date.now().toString(),
    Type: 'checkbox',
    Name: 'New Checkbox',
    Description: 'Checkbox created on backend',
    EmojiIcon: 'Star',
    NameVisible: false,
    Chosen: {
      Monday: false,
      Tuesday: false,
      Wednesday: false,
      Thursday: false,
      Friday: false,
      Saturday: false,
      Sunday: false,
    },
    Width: 50,
    CheckboxColor: 'green',
  },
  numberbox: {
    ColumnId: Date.now().toString(),
    Type: 'numberbox',
    Name: 'New Numberbox',
    Description: 'Numberbox created on backend',
    EmojiIcon: 'Star',
    NameVisible: false,
    Chosen: {
      Monday: '',
      Tuesday: '',
      Wednesday: '',
      Thursday: '',
      Friday: '',
      Saturday: '',
      Sunday: '',
    },
    Width: 60,
  },
  text: {
    ColumnId: Date.now().toString(),
    Type: 'text',
    Name: 'New Text',
    Description: 'Text created on backend',
    EmojiIcon: 'Star',
    NameVisible: true,
    Chosen: {
      Monday: '',
      Tuesday: '',
      Wednesday: '',
      Thursday: '',
      Friday: '',
      Saturday: '',
      Sunday: '',
    },
    Width: 130,
  },
  'multi-select': {
    ColumnId: Date.now().toString(),
    Type: 'multi-select',
    Name: 'New Multi-Select',
    Description: 'Multi-select created on backend',
    EmojiIcon: 'Star',
    NameVisible: true,
    Options: ['Option 1', 'Option 2'],
    TagColors: {
      'Option 1': 'blue',
      'Option 2': 'green',
    },
    Chosen: {
      Monday: '',
      Tuesday: '',
      Wednesday: '',
      Thursday: '',
      Friday: '',
      Saturday: '',
      Sunday: '',
    },
    Width: 90,
  },
  multicheckbox: {
    ColumnId: Date.now().toString(),
    Type: 'multicheckbox',
    Name: 'New Multi Checkbox',
    Description: 'Multi-checkbox created on backend',
    EmojiIcon: 'Circle',
    NameVisible: false,
    Options: ['Task 1', 'Task 2'],
    TagColors: {
      'Task 1': 'blue',
      'Task 2': 'green',
    },
    Chosen: {
      Monday: '',
      Tuesday: '',
      Wednesday: '',
      Thursday: '',
      Friday: '',
      Saturday: '',
      Sunday: '',
    },
    Width: 50,
  },
  tasktable: {
    ColumnId: Date.now().toString(),
    Type: 'tasktable',
    Name: 'New Task List',
    Description: 'Task table created on backend',
    EmojiIcon: 'ListTodo',
    NameVisible: true,
    Options: ['Task 1', 'Task 2'],
    TagColors: {
      'Task 1': 'blue',
      'Task 2': 'green',
    },
    Chosen: {
      global: [],
    },
    Width: 150,
  },
});

const getSettingsTemplates = () => ({
  theme: {
    darkMode: false,
    accentColor: 'blue',
    autoThemeSettings: {
      enabled: false,
      startTime: '08:00',
      endTime: '20:00',
    },
  },
  table: {
    columnOrder: [],
    showSummaryRow: false,
    compactMode: false,
    stickyHeader: true,
  },
  ui: {
    animations: true,
    tooltips: true,
    confirmDelete: true,
  },
});

module.exports = { getColumnTemplates, getSettingsTemplates };
