const themes = {
  standard: {
    light: {
      border: 'border-gray-200',
      text: 'text-blue-700',
      textAccent: 'text-blue-600',
      textTableValues: 'text-gray-600',
      textTableRealValues: 'text-gray-500',
      //
      linkActive: 'bg-blue-600 text-white',
      linkInactive: 'text-gray-600 hover:scale-105 hover:bg-blue-50',
      //
      iconActive: 'text-white',
      iconInactive: 'text-gray-600',
      toggleIcon: 'text-blue-500',
      hover: 'hover:bg-blue-100',
      sidebarToggleHover: 'hover:bg-blue-50',
      tableHeader: 'bg-gray-50 ',
      tableHeaderText: 'text-gray-700',
      tableBodyBg: 'bg-white',
      tableSummaryText: 'text-gray-700',
      scrollbarTrack: 'rgba(241, 241, 241, 0.2)',
      scrollbarThumb: 'rgba(156, 163, 175, 0.5)',
      scrollbarThumbHover: 'rgba(107, 114, 128, 0.7)',
      settingsSectionSelectorBg: 'bg-blue-50',

      bubbleBtn: {
        standard: 'bg-blue-600 hover:bg-blue-700 text-white',
        delete: 'bg-red-500 hover:bg-red-600 text-white',
        clear: 'bg-gray-100 hover:bg-gray-200 text-gray-600',
      },
      background: 'bg-white',
    },
    dark: {
      background: 'bg-gray-900',
      border: 'border-gray-700',
      text: 'text-blue-200',
      textAccent: 'text-blue-400',
      textTableValues: 'text-gray-200',
      textTableRealValues: 'text-gray-300',
      linkActive: 'bg-blue-500 scale-110 shadow-md text-white',
      linkInactive: 'text-gray-300 hover:scale-105 hover:bg-gray-700',
      iconActive: 'text-white',
      iconInactive: 'text-gray-300',
      toggleIcon: 'text-blue-400',
      hover: 'hover:bg-blue-800',
      sidebarToggleHover: 'hover:bg-gray-700',
      tableHeaderText: 'text-gray-300',
      tableHeader: 'bg-gray-800',
      tableBodyBg: 'bg-gray-800',
      tableSummaryText: 'text-gray-200',
      scrollbarTrack: 'rgba(55, 65, 81, 0.5)',
      scrollbarThumb: 'rgba(156, 163, 175, 0.7)',
      scrollbarThumbHover: 'rgba(107, 114, 128, 0.9)',
      settingsSectionSelectorBg: 'bg-gray-700',
      bubbleBtn: {
        standard: 'bg-blue-500 hover:bg-blue-600 text-white',
        delete: 'bg-red-400 hover:bg-red-500 text-white',
        clear: 'bg-gray-700 hover:bg-gray-600 text-gray-300',
      },
    },
  },
  nature: {
    light: {
      background: 'bg-green-50',
      border: 'border-green-200',
      text: 'text-green-800',
      textAccent: 'text-green-700',
      textTableValues: 'text-gray-700',
      textTableRealValues: 'text-gray-600',
      linkActive: 'bg-green-600 scale-110 shadow-md text-white',
      linkInactive: 'text-green-700 hover:scale-105 hover:bg-green-100',
      iconActive: 'text-white',
      iconInactive: 'text-green-700',
      toggleIcon: 'text-green-600',
      hover: 'hover:bg-green-100',
      sidebarToggleHover: 'hover:bg-green-100',
      tableHeader: 'bg-green-100 border-green-200',
      tableHeaderText: 'text-gray-700',
      tableBodyBg: 'bg-white',
      tableSummaryText: 'text-green-800',
      scrollbarTrack: 'rgba(220, 252, 231, 0.2)',
      scrollbarThumb: 'rgba(134, 239, 172, 0.5)',
      scrollbarThumbHover: 'rgba(34, 197, 94, 0.7)',
      settingsSectionSelectorBg: 'bg-green-100',
      bubbleBtn: {
        standard: 'bg-green-600 hover:bg-green-700 text-white',
        delete: 'bg-red-500 hover:bg-red-600 text-white',
        clear: 'bg-gray-100 hover:bg-gray-200 text-gray-600',
      },
    },
    dark: {
      background: 'bg-green-900',
      border: 'border-green-700',
      text: 'text-green-200',
      textAccent: 'text-green-300',
      textTableValues: 'text-gray-300',
      textTableRealValues: 'text-gray-400',
      linkActive: 'bg-green-700 text-white',
      linkInactive: 'text-green-300 hover:scale-105 hover:bg-green-800',
      iconActive: 'text-white',
      iconInactive: 'text-green-300',
      toggleIcon: 'text-green-400',
      hover: 'hover:bg-green-800',
      sidebarToggleHover: 'hover:bg-green-800',
      tableHeader: 'bg-green-800 border-green-600',
      tableHeaderText: 'text-gray-300',
      tableBodyBg: 'bg-green-900',
      tableSummaryText: 'text-green-200',
      scrollbarTrack: 'rgba(22, 101, 52, 0.5)',
      scrollbarThumb: 'rgba(134, 239, 172, 0.7)',
      scrollbarThumbHover: 'rgba(34, 197, 94, 0.9)',
      settingsSectionSelectorBg: 'bg-green-800',
      bubbleBtn: {
        standard: 'bg-green-500 hover:bg-green-600 text-white',
        delete: 'bg-red-400 hover:bg-red-500 text-white',
        clear: 'bg-gray-700 hover:bg-gray-600 text-gray-300',
      },
    },
  },
};
export default themes;
