const themes = {
  blue: {
    light: {
      background: "bg-blue-50",
      border: "border-blue-100",
      text: "text-blue-700",
      textAccent: "text-blue-500",
      linkActive: "bg-blue-500 scale-110 shadow-md text-white",
      linkInactive: "text-blue-700 hover:scale-105 hover:bg-blue-100",
      iconActive: "text-white",
      iconInactive: "text-blue-600",
      toggleIcon: "text-blue-500",
    },
    dark: {
      background: "bg-blue-950",
      border: "border-blue-900",
      text: "text-blue-200",
      textAccent: "text-blue-400",
      linkActive: "bg-blue-600 scale-110 shadow-md text-white",
      linkInactive: "text-blue-200 hover:scale-105 hover:bg-blue-800",
      iconActive: "text-white",
      iconInactive: "text-blue-300",
      toggleIcon: "text-blue-400",
    },
  },
  peach: {
    light: {
      background: "bg-orange-50",
      border: "border-orange-100",
      text: "text-orange-700",
      textAccent: "text-orange-500",
      linkActive: "bg-orange-400 scale-110 shadow-md text-white",
      linkInactive: "text-orange-700 hover:scale-105 hover:bg-orange-100",
      iconActive: "text-white",
      iconInactive: "text-orange-600",
      toggleIcon: "text-orange-400",
    },
    dark: {
      background: "bg-[#1a1410]", // темно-коричнево-персиковий вайб
      border: "border-orange-900",
      text: "text-orange-200",
      textAccent: "text-orange-400",
      linkActive: "bg-orange-500 scale-110 shadow-md text-white",
      linkInactive: "text-orange-200 hover:scale-105 hover:bg-orange-800",
      iconActive: "text-white",
      iconInactive: "text-orange-300",
      toggleIcon: "text-orange-400",
    },
  },
  lavender: {
    light: {
      background: "bg-purple-50",
      border: "border-purple-100",
      text: "text-purple-700",
      textAccent: "text-purple-500",
      linkActive: "bg-purple-400 scale-110 shadow-md text-white",
      linkInactive: "text-purple-700 hover:scale-105 hover:bg-purple-100",
      iconActive: "text-white",
      iconInactive: "text-purple-600",
      toggleIcon: "text-purple-400",
    },
    dark: {
      background: "bg-purple-950",
      border: "border-purple-900",
      text: "text-purple-200",
      textAccent: "text-purple-400",
      linkActive: "bg-purple-500 scale-110 shadow-md text-white",
      linkInactive: "text-purple-200 hover:scale-105 hover:bg-purple-800",
      iconActive: "text-white",
      iconInactive: "text-purple-300",
      toggleIcon: "text-purple-400",
    },
  },
  mint: {
    light: {
      background: "bg-green-50",
      border: "border-green-100",
      text: "text-green-700",
      textAccent: "text-green-500",
      linkActive: "bg-green-400 scale-110 shadow-md text-white",
      linkInactive: "text-green-700 hover:scale-105 hover:bg-green-100",
      iconActive: "text-white",
      iconInactive: "text-green-600",
      toggleIcon: "text-green-400",
    },
    dark: {
      background: "bg-green-950",
      border: "border-green-900",
      text: "text-green-200",
      textAccent: "text-green-400",
      linkActive: "bg-green-500 scale-110 shadow-md text-white",
      linkInactive: "text-green-200 hover:scale-105 hover:bg-green-800",
      iconActive: "text-white",
      iconInactive: "text-green-300",
      toggleIcon: "text-green-400",
    },
  },
  rose: {
    light: {
      background: "bg-pink-50",
      border: "border-pink-100",
      text: "text-pink-700",
      textAccent: "text-pink-500",
      linkActive: "bg-pink-400 scale-110 shadow-md text-white",
      linkInactive: "text-pink-700 hover:scale-105 hover:bg-pink-100",
      iconActive: "text-white",
      iconInactive: "text-pink-600",
      toggleIcon: "text-pink-400",
    },
    dark: {
      background: "bg-pink-950",
      border: "border-pink-900",
      text: "text-pink-200",
      textAccent: "text-pink-400",
      linkActive: "bg-pink-500 scale-110 shadow-md text-white",
      linkInactive: "text-pink-200 hover:scale-105 hover:bg-pink-800",
      iconActive: "text-white",
      iconInactive: "text-pink-300",
      toggleIcon: "text-pink-400",
    },
  },
};

export default themes;
