@startuml


TableUI --> tableSlice: "GIVE ME TABLE STATE"

tableSlice --> IndexedDB: "give me json with columns objects"
IndexedDB --> tableSlice: "here is json with columns objects"


tableSlice --> TableUI: "here is table state"

TableUI --> tableSlice: "SAVE TABLE STATE"
tableSlice --> IndexedDB: "save json with columns objects"
IndexedDB --> tableSlice: "ok, saved"
tableSlice --> TableUI: "table state saved"
@enduml